### ISSUE TITLE
Prevent unpublishing singletons

### ISSUE THREAD

**Issue by marcusforsberg** [plsrd/sanity-plugin-singleton-tools#2]
Hi,

First off, thanks for releasing this plugin, it works really well! 😊 We were previously using our own simple internal plugin for this but are scrapping that in favour of this.

The one difference from our old approach is that we used to also disable the Unpublish action on singletons, the logic being that a singleton such as Site Settings shouldn't ever be possible to accidentally unpublish - it needs to always be "available".

Would you consider adding the same approach here, perhaps as another option on the schema? I can open a PR for it, just wanted to see if you'd be interested first. ✨

**Comment by plsrd** [comment]
Yes! That would be an helpful addition. I debated whether or not to allow it in the first place. I'd happily accept a PR!
