### ISSUE TITLE
Creating a Singletron

### ISSUE THREAD

**Issue by miller-design** [plsrd/sanity-plugin-singleton-tools#4]
Hi there,

Can I say great plugin find this super useful for my projects.

I've come across a small bug where when setting up my singletron schema if I have set the singltron options to true before i have published/created any content for that document type it doesn't let me make one.

if I set the value to false, I can create my singleton page but obviously, this lets me create more than one, so setting it back to true after the page is created removes the expected functionality.

with the option set to true
<img width="550" alt="Screenshot 2024-05-30 at 12 30 06" src="https://github.com/plsrd/sanity-plugin-singleton-tools/assets/72648825/cf74d9e8-2e74-48fd-a06a-aba989998ad7">
<img width="384" alt="Screenshot 2024-05-30 at 12 31 41" src="https://github.com/plsrd/sanity-plugin-singleton-tools/assets/72648825/fabf4c7c-8ae3-4eca-ad04-88decc849105">

with the option disabled
<img width="568" alt="Screenshot 2024-05-30 at 12 31 57" src="https://github.com/plsrd/sanity-plugin-singleton-tools/assets/72648825/0d002491-1140-49d4-997b-1b8d87f3c26b">
<img width="362" alt="Screenshot 2024-05-30 at 12 32 25" src="https://github.com/plsrd/sanity-plugin-singleton-tools/assets/72648825/8e60e8a9-c899-4938-8858-fbc9647aac8b">

I followed your steps for installing the package, creating the scheme, and copying the structure so I'm not sure if you have a bug here or if I'm missing a step. But any guidance would be greatly appreciated.

Cheers,
Jack

**Comment by frankypixels** [comment]
Same happening when you create a second singleton

**Comment by miller-design** [comment]
Hi there, yeh the issue still persists even if i have multiple singletons set in my studio.
